# -*- coding: utf-8 -*-
"""2025AA05748.StreamlitApp.assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hV3TlBmgB_Ou3gtcNcA_TMogmHVwnfNL
"""

import streamlit as st
import numpy as np
import cv2
import joblib
import tensorflow as tf
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# ============================
# Page Config
# ============================
st.set_page_config(
    page_title="Cat vs Dog Classification (CIFAR-10)",
    layout="wide"
)

st.title("🐱🐶 Cat vs Dog Classification using Classical ML Models")
st.markdown("Dataset: **CIFAR-10 (Cat vs Dog subset)**")

# ============================
# Load Models & Preprocessors
# ============================
@st.cache_resource
def load_artifacts():
    scaler = joblib.load("model/scaler.pkl")
    pca = joblib.load("model/pca.pkl")

    models = {
        "Logistic Regression": joblib.load("model/logistic_regression.pkl"),
        "Decision Tree": joblib.load("model/decision_tree.pkl"),
        "KNN": joblib.load("model/knn.pkl"),
        "Naive Bayes": joblib.load("model/naive_bayes.pkl"),
        "Random Forest": joblib.load("model/random_forest.pkl"),
        "XGBoost": joblib.load("model/xgboost.pkl")
    }
    return scaler, pca, models


scaler, pca, models = load_artifacts()

# ============================
# Sidebar Controls
# ============================
st.sidebar.header("⚙️ Model Selection")

selected_model_name = st.sidebar.selectbox(
    "Choose ML Model",
    list(models.keys())
)

# ============================
# Load CIFAR-10 Test Data
# ============================
st.subheader("📂 CIFAR-10 Test Data (Cat vs Dog)")

if st.button("Load CIFAR-10 Test Samples"):
    (_, _), (X_test_full, y_test_full) = tf.keras.datasets.cifar10.load_data()

    y_test_full = y_test_full.flatten()

    CAT_LABEL = 3
    DOG_LABEL = 5

    mask = (y_test_full == CAT_LABEL) | (y_test_full == DOG_LABEL)

    X_test = X_test_full[mask]
    y_true = y_test_full[mask]
    y_true = np.where(y_true == CAT_LABEL, 0, 1)

    # ============================
    # Feature Extraction
    # ============================
    IMG_SIZE = 64
    features = []

    for img in X_test:
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img = img / 255.0
        features.append(img.flatten())

    X_features = np.array(features)

    # Scale + PCA
    X_scaled = scaler.transform(X_features)
    X_pca = pca.transform(X_scaled)

    # ============================
    # Prediction
    # ============================
    model = models[selected_model_name]

    y_pred = model.predict(X_pca)
    y_prob = model.predict_proba(X_pca)[:, 1]

    # ============================
    # Metrics Display
    # ============================
    st.subheader("📊 Evaluation Metrics")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Accuracy", round(accuracy_score(y_true, y_pred), 3))
        st.metric("Precision", round(precision_score(y_true, y_pred), 3))

    with col2:
        st.metric("Recall", round(recall_score(y_true, y_pred), 3))
        st.metric("F1 Score", round(f1_score(y_true, y_pred), 3))

    with col3:
        st.metric("MCC", round(matthews_corrcoef(y_true, y_pred), 3))
        st.metric("AUC", round(roc_auc_score(y_true, y_prob), 3))

    # ============================
    # Confusion Matrix
    # ============================
    st.subheader("🧮 Confusion Matrix")

    cm = confusion_matrix(y_true, y_pred)
    cm_df = pd.DataFrame(
        cm,
        columns=["Predicted Cat", "Predicted Dog"],
        index=["Actual Cat", "Actual Dog"]
    )

    st.dataframe(cm_df)

    # ============================
    # Classification Report
    # ============================
    st.subheader("📄 Classification Report")
    report = classification_report(
        y_true,
        y_pred,
        target_names=["Cat", "Dog"],
        output_dict=True
    )
    st.dataframe(pd.DataFrame(report).transpose())